export const CONSTANTES = {

    // COMUNS
    TITULO_SITE: 'HoraCerta',

    // MENU
    HOME: '/',
    RECURSOS: '/recursos',
    PRECOS: '/precos',
    COMO_FUNCIONA: '/comoFunciona',
    REGISTRO: '/registro',
    LOGIN: '/login',
    CADASTRO: '/cadastro',
    EMPRESA: '/empresa',
    TITULO_HOME: 'Home',
    TITULO_MENU_RECURSOS: 'Recursos',
    TITULO_MENU_PRECOS: 'Preços',
    TITULO_MENU_COMO_FUNCIONA: 'Como funciona',

    // PAGINA HOME
    TITULO_PRINCIPAL: 'Controle de ponto que seus colaboradores vão adorar usar',
    SUBTITULO_PRINCIPAL: 'Uma ferramenta simples e intuitiva para registro e gestão de ponto. Sem complicações, sem burocracias.',
    BOTAO_COMECAR: 'Começar gratuitamente →',
    BOTAO_LOGIN: 'Já tem uma conta? Faça login',
    TITULO_RECURSOS: 'Recursos que facilitam sua gestão',
    SUBTITULO_RECURSOS: 'Tudo que você precisa para gerenciar o ponto dos seus terceirizados',
    TITULO_CARDS: 'Recursos que facilitam sua gestão',
    SUBTITULO_CARDS: 'Tudo que você precisa para gerenciar o ponto dos seus terceirizados',
    CARD_RECURSOS_01_TITULO: 'Registro Simplificado',
    CARD_RECURSOS_01_SUBTITULO: 'Registre o ponto de forma rápida e intuitiva, sem complicações ou burocracias.',
    CARD_RECURSOS_02_TITULO: 'Edição Flexível',
    CARD_RECURSOS_02_SUBTITULO: 'Faça ajustes nos registros quando necessário, com histórico completo de alterações.',
    CARD_RECURSOS_03_TITULO: 'Relatórios Detalhados',
    CARD_RECURSOS_03_SUBTITULO: 'Gere relatórios personalizados e exporte em PDF ou Excel.',
    CARD_RECURSOS_04_TITULO: 'Integração com Sistemas Externos',
    CARD_RECURSOS_04_SUBTITULO: 'Conecte-se a sistemas de RH, controle de acesso e outros para uma gestão mais eficiente.',
    CARD_RECURSOS_05_TITULO: 'Segurança e Confidencialidade',
    CARD_RECURSOS_05_SUBTITULO: 'Seus dados são protegidos com criptografia e segurança avançada.',
    CARD_RECURSOS_06_TITULO: 'Suporte ao Colaborador',
    CARD_RECURSOS_06_SUBTITULO: 'Ofereça suporte ao colaborador com relatórios de ponto e acesso aos dados.',
    TITULO_EMPRESA: 'HoraCerta para Empresas',
    SUBTITULO_EMPRESA: 'Soluções personalizadas para grandes empresas. Integração com sistemas existentes, suporte dedicado e muito mais.',
    COMING_SOON: 'Em breve',
    ICONE_EMPRESA: '🏢',

    // PAGINA RECURSOS
    TITULO_RECURSOS_COMPLETOS: 'Recursos Completos',
    SUBTITULO_RECURSOS_COMPLETOS: 'Conheça todas as funcionalidades do HoraCerta',
    // ---- CARDS REGISTRO DE PONTO ----
    CARD_REGISTRO_DE_PONTO_TITULO: 'Registro de Ponto',
    CARD_REGISTRO_DE_PONTO_01_TITULO: 'Registro Simplificado',
    CARD_REGISTRO_DE_PONTO_01_ITEM_01: 'Interface intuitiva e fácil de usar',
    CARD_REGISTRO_DE_PONTO_01_ITEM_02: 'Registro rápido de entrada e saída',
    CARD_REGISTRO_DE_PONTO_01_ITEM_03: 'Confirmação instantânea',
    CARD_REGISTRO_DE_PONTO_02_TITULO: 'Edição Flexível',
    CARD_REGISTRO_DE_PONTO_02_ITEM_01: 'Ajuste rápido e fácil',
    CARD_REGISTRO_DE_PONTO_02_ITEM_02: 'Histórico completo de alterações',
    CARD_REGISTRO_DE_PONTO_02_ITEM_03: 'Compatível com dispositivos móveis',
    CARD_REGISTRO_DE_PONTO_03_TITULO: 'Notificações',
    CARD_REGISTRO_DE_PONTO_03_ITEM_01: 'Lembretes de registro',
    CARD_REGISTRO_DE_PONTO_03_ITEM_02: 'Alertas de inconsistências',
    CARD_REGISTRO_DE_PONTO_03_ITEM_03: 'Confirmações por email',
    // ---- CARDS GESTÃO E EDICAO ----
    CARD_GESTÃO_E_EDICAO_TITULO: 'Gestão e Edição',
    CARD_GESTÃO_E_EDICAO_01_TITULO: 'Edição Flexível',
    CARD_GESTÃO_E_EDICAO_01_ITEM_01: 'Ajuste de horários',
    CARD_GESTÃO_E_EDICAO_01_ITEM_02: 'Adição de justificativas',
    CARD_GESTÃO_E_EDICAO_01_ITEM_03: 'Anexo de documentos',
    CARD_GESTÃO_E_EDICAO_02_TITULO: 'Gestão Simplificada',
    CARD_GESTÃO_E_EDICAO_02_ITEM_01: 'Visão geral dos registros',
    CARD_GESTÃO_E_EDICAO_02_ITEM_02: 'Organização por períodos',
    CARD_GESTÃO_E_EDICAO_02_ITEM_03: 'Filtros avançados',
    CARD_GESTÃO_E_EDICAO_03_TITULO: 'Backup Automático',
    CARD_GESTÃO_E_EDICAO_03_ITEM_01: 'Dados sempre seguros',
    CARD_GESTÃO_E_EDICAO_03_ITEM_02: 'Histórico completo',
    CARD_GESTÃO_E_EDICAO_03_ITEM_03: 'Recuperação facilitada',
    // ---- CARDS RELATÓRIOS E EXPORTAÇÃO ----
    CARD_RELATÓRIOS_E_EXPORTAÇÃO_TITULO: 'Relatórios e Exportação',
    CARD_RELATÓRIOS_E_EXPORTAÇÃO_01_TITULO: 'Relatórios Detalhados',
    CARD_RELATÓRIOS_E_EXPORTAÇÃO_01_ITEM_01: 'Relatórios personalizados',
    CARD_RELATÓRIOS_E_EXPORTAÇÃO_01_ITEM_02: 'Múltiplos formatos',
    CARD_RELATÓRIOS_E_EXPORTAÇÃO_01_ITEM_03: 'Exportação facilitada',
    CARD_RELATÓRIOS_E_EXPORTAÇÃO_02_TITULO: 'Análise de Dados',
    CARD_RELATÓRIOS_E_EXPORTAÇÃO_02_ITEM_01: 'Visualização de tendências',
    CARD_RELATÓRIOS_E_EXPORTAÇÃO_02_ITEM_02: 'Estatísticas detalhadas',
    CARD_RELATÓRIOS_E_EXPORTAÇÃO_02_ITEM_03: 'Insights importantes',
    CARD_RELATÓRIOS_E_EXPORTAÇÃO_03_TITULO: 'Segurança',
    CARD_RELATÓRIOS_E_EXPORTAÇÃO_03_ITEM_01: 'Dados criptografados',
    CARD_RELATÓRIOS_E_EXPORTAÇÃO_03_ITEM_02: 'Backup regular',
    CARD_RELATÓRIOS_E_EXPORTAÇÃO_03_ITEM_03: 'Conformidade com LGPD',
    // ---- BOTTON



}